AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app

  Registered Users
  
Parameters:
  AppStage:
    Type: String
    Default: Dev 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RegisterUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: 
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole    
      AutoPublishAlias: Test
      CodeUri: registered-users/
      Handler: registered-users-lambda.handler
      Runtime: nodejs10.x
      Events:
        SignupNewUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /signup-new-user/
            Method: post
            RestApiId: !Ref WebApi
        LoginUser:
          Type: Api
          Properties:
            Path: /login-user/
            Method: post
            RestApiId: !Ref WebApi
      Environment:
        Variables:
          AWS_STAGE: { Ref: "AppStage" }
          DYNAMODB_ENDPOINT: "null" 
  WebApi:
    Type: AWS::Serverless::Api
    Properties: 
      StageName: !Ref AppStage 
  DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "Name"
          AttributeType: "S"
        - AttributeName: "Phone"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "Phone"
          KeyType: "HASH"
        - AttributeName: "Name"
          KeyType: "RANGE"          
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "UserAccounts_${AppStage}"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RegisteredUsersApi:
    Description: "API Gateway endpoint URL for Registered Users function"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/"
  RegisteredUsersFunction:
    Description: "Registered Users Lambda Function ARN"
    Value: !GetAtt RegisterUserFunction.Arn
  RegisteredUsersFunctionIamRole:
    Description: "Implicit IAM Role created for Registered Users function"
    Value: !GetAtt RegisterUserFunctionRole.Arn
