AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app

  Signup User
  
Parameters:
  AppStage:
    Type: String
    Default: Dev 
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions

Globals:
  Function:
    Timeout: 3

Resources:
  UserAccountFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Policies: 
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole  
        - AmazonS3FullAccess  
      AutoPublishAlias: Test
      CodeUri: user-account/
      Handler: user-account-lambda.handler
      Runtime: nodejs10.x
      Events:
        SignupUser:
          Type: Api 
          Properties:
            Path: /signup-user/
            Method: post
            RestApiId: !Ref WebApi
        LoginUser:
          Type: Api
          Properties:
            Path: /login-user/
            Method: post
            RestApiId: !Ref WebApi
      Environment:
        Variables:
          AWS_STAGE: { Ref: "AppStage" }
          DYNAMODB_ENDPOINT: "null" 
  WebApi:
    Type: AWS::Serverless::Api
    Properties: 
      StageName: !Ref AppStage 
  DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "Name"
          AttributeType: "S"
        - AttributeName: "Phone"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "Phone"
          KeyType: "HASH"
        - AttributeName: "Name"
          KeyType: "RANGE"          
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub "UserAccounts_${AppStage}"
Outputs:
  UserAccountApi:
    Description: "API Gateway endpoint URL for User account function"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/"
  UserAccountFunction:
    Description: "User Account Lambda Function ARN"
    Value: !GetAtt UserAccountFunction.Arn
  UserAccountFunctionIamRole:
    Description: "Implicit IAM Role created for User account function"
    Value: !GetAtt UserAccountFunctionRole.Arn
